# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop, experimental, master ]
  pull_request:
    branches: [ develop, experimental, master ]

jobs:
  bundle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM Install
      run: |
        npm ci --no-optional
        npm rebuild node-sass    
        npm run build:assets

  lint:
    needs: bundle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}      
    - name: Lint
      run: npm run lint
    - name: Shellcheck
      run: ./run-shellcheck.sh

  test-api:
    needs: [bundle, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Web API - Test
      run: npm run test:api
    - name: Normalize Coverage for SonarQube
      run: npx istanbul-combine -d web-api/coverage web-api/coverage/coverage-final.json

  test-shared:
    needs: [bundle, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}      
    - name: Shared - Test
      run: npm run test:shared

  test-client-unit:
    needs: [bundle, lint]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}      
    - name: Web Client - Unit Test
      run: npm run test:client:unit
